name: Build toolchain
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Check out linux-new
        uses: actions/checkout@v3
        with:
          repository: 'OpenNoah/linux-new'
          ref: 'np-5.17.3'
          path: 'linux'
      - name: Configure linux
        run: |
          cd linux
          ARCH=mips make noah_np1380_defconfig
      - name: Build mipsel-linux
        run: |
          PATH="$PATH:$PWD/mipsel-linux/bin" make -j2 KERNEL="$PWD/linux"
      - name: Archive
        run: |
          KERNEL="$PWD/linux" ./release.sh
          echo "RELEASE=$(echo *.tar.xz)" >> $GITHUB_ENV
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.RELEASE }}
          path: ${{ env.RELEASE }}
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ env.RELEASE }}
